src/main/java/model/AuthenticatedUser.java
package model;

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;

import lombok.Getter;
import lombok.Setter;

@Entity
@PrimaryKeyJoinColumn(referencedColumnName="id")
public class AuthenticatedUser extends User {
	@Getter@Setter
	@Column(nullable=false, unique=true)
	String email;
	
	@Getter@Setter
	@Column(nullable=false)
	String password;
	
	@Getter@Setter
	@Column(nullable=false)
	Boolean manager;
}

src/main/java/model/Event.java
package model;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import java.time.Instant;
import java.util.List;

@Entity
public class Event {
	@Getter @Setter
	@GeneratedValue
	@Id long id;
			
	@Column(nullable=false)
	@Getter @Setter
	String name;
	
	@Column(nullable=false)
	@Getter @Setter
	String teaser = "[default teaser]";
	
	@Column(nullable=false)
	@Getter @Setter
	String description = "[default description]";
	
	@Column(nullable=false)
	@Getter @Setter
	Instant startDate;

	@Getter @Setter
	boolean released;
	
	@Column(nullable=false)
	@Getter @Setter
	Instant endDate;

	@Column(nullable=false)
	@Getter @Setter
	long capacity;
	
	@ManyToOne
	@JoinColumn(name = "organizer", referencedColumnName = "id", nullable = false)
	@Getter@Setter
	AuthenticatedUser organizer;

	@OneToMany(mappedBy = "event")
	@Getter@Setter
	List<Tickets> tickets;
}

src/main/java/model/InstantConverter.java
package model;

import javax.persistence.AttributeConverter;
import javax.persistence.Converter;
import java.sql.Timestamp;
import java.time.Instant;

@Converter(autoApply = true)
public class InstantConverter implements AttributeConverter<Instant, Timestamp> {
	public Instant convertToEntityAttribute(Timestamp date) {
		if (date == null) {return null;}
		return date.toInstant();
	}

	public Timestamp convertToDatabaseColumn(Instant instant) {
		if (instant == null) {return null;}
		return Timestamp.from(instant);
	}
}

src/main/java/model/Tickets.java
package model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
public class Tickets {
	@Embeddable
	@AllArgsConstructor
	@NoArgsConstructor
	public static class Key{
		@Column(name = "event", nullable = false, insertable = false, updatable = false)
		long event;
		@Column(name = "id", nullable = false)
		@Getter
		int id;
	}
	@Getter@Setter @EmbeddedId Key key;

	@ManyToOne
	@JoinColumn(name="user", referencedColumnName = "id", nullable = false)
	@Getter@Setter
	User user;

	@ManyToOne
	@JoinColumn(name = "event", referencedColumnName = "id", insertable = true, updatable = false, nullable = false)
	@Getter@Setter
	Event event;

	@Column(name = "amount", nullable = false)
	@Getter@Setter
	long amount;
}

src/main/java/model/User.java
package model;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class User {
	@Getter@Setter
	@Id @GeneratedValue long id;

	@Getter@Setter
	@Column(nullable=false)
	private String name;
}

src/main/java/state/SessionBean.java
package state;
import lombok.Getter;
import lombok.Setter;
import model.AuthenticatedUser;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class SessionBean implements Serializable {
	@Getter@Setter
	private AuthenticatedUser currentUser = null;
	public boolean isLoggedIn() {return currentUser != null;}
	public void logout(){
		currentUser=null;
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	}
}

src/main/webapp/created.xhtml
<created>#{saveEvent.id}</created>

src/main/webapp/genericSuccess.xhtml
<success />

src/main/webapp/index.xhtml
<html 	
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:core="http://java.sun.com/jsp/jstl/core">
<head><link rel="stylesheet" href="style.css" /></head>
<h:body rendered="#{not eventList.errorResponse}">
	<header>
		<div><h1>Event Planner</h1></div>
		<form><input name="q" placeholder="Filtern" value="#{eventList.searchWord}" /><button>Alle Veranstaltungen</button><button name="own">Meine Veranstaltungen</button></form>
		<h:panelGroup rendered="#{not sessionBean.loggedIn}"><a href="#login">Login</a></h:panelGroup>
		<h:form rendered="#{sessionBean.loggedIn}" id="logout">#{sessionBean.currentUser.name}<h:commandButton action="#{logout.logout}" value="Logout" /></h:form>
	</header>
	<h:panelGroup rendered="#{eventList.ownEvents}"><h1>Meine Veranstaltungen</h1></h:panelGroup>
	<h:panelGroup rendered="#{not eventList.ownEvents}"><h1>Alle Veranstaltungen</h1></h:panelGroup>
	<ul class="event-list">
		<core:if test="#{sessionBean.loggedIn and sessionBean.currentUser.manager}"><li>
			<h2>Neue Veranstaltung</h2>
			<h:form p:id="save-form">
				<h:inputHidden value="#{saveEvent.id}" p:data-param="id"/>
				<label>Name<h:inputText value="#{saveEvent.name}" p:data-param="name" /></label>
				<label>Teaser<h:inputTextarea value="#{saveEvent.teaser}" p:data-param="teaser" /></label>
				<label>Beschreibung<h:inputTextarea value="#{saveEvent.description}" p:data-param="description" /></label>
				<label>Anfangsdatum (UTC)<h:inputText value="#{saveEvent.startDate}" p:type="datetime-local" p:data-param="startDate" /></label>
				<label>Enddatum (UTC)<h:inputText value="#{saveEvent.endDate}" p:type="datetime-local" p:data-param="endDate" /></label>
				<label>Anzahl Tickets<h:inputText value="#{saveEvent.capacity}" p:type="number" p:data-param="capacity" /></label>
				<h:commandButton action="#{saveEvent.save}" value="Veranstaltung erstellen" />
			</h:form>
		</li></core:if>

		<ui:repeat value="#{eventList.events}" var="event"><li id="event#{event.id}" data-id="#{event.id}" class="foldable folded">
			<dl class="time-info">
				<dt>Fängt an:</dt><dd data-field="startDate">#{event.startDate}</dd>
				<dt>Endet:</dt><dd data-field="endDate">#{event.endDate}</dd>
			</dl>
			<h2 data-field="name" class="event-name">#{event.name}</h2>
			<p data-field="teaser" class="teaser">#{event.teaser}</p>
			<h:form rendered="#{releaseEvent.isOrganizedByMe(event) and not event.released}" styleClass="editable-marker release-form">
				<h:commandButton action="#{releaseEvent.release(event)}" value="Event freigeben" />
			</h:form>
			<div class="fold"></div>
			<p data-field="description" class="description">#{event.description}</p>
			<p class="num-tickets"><span>#{event.capacity}</span> Tickets zur Reservierung<h:panelGroup rendered="#{event.released}">, #{reserveTicket.getAvailableTickets(event)} noch verfügbar</h:panelGroup></p>
			<h:panelGroup rendered="#{event.released}" styleClass="reserve-button"><a href="#reserve" data-action="reserveEvent">Tickets reservieren</a></h:panelGroup>
			<div class="reservations"><h:panelGroup rendered="#{event.released}">Reservierungen:<!--TODO: only if organizer or has tickets-->
				<ul><ui:repeat value="#{releaseEvent.getMyReservations(event)}" var="reservation">
					<li>#{reservation.amount} Tickets: Reservierungscode #{event.id}-#{reservation.key.id}</li>
				</ui:repeat></ul>
			</h:panelGroup></div>
		</li></ui:repeat>
	</ul>
	<h:panelGroup styleClass="modal" rendered="#{not sessionBean.loggedIn}"><div class="tabs"><div class="tab-header"><a href="#login" class="active">Einloggen</a><a href="#register">Registrieren</a></div>
		<div class="tab-body">
			<h:form id="login">
				<label>E-Mail<h:inputText value="#{login.email}" p:data-param="email" p:type="email" p:autocomplete="username" /></label>
				<label>Passwort<h:inputSecret value="#{login.password}" p:data-param="password" p:autocomplete="current-password" /></label>
				<h:commandButton action="#{login.login}" value="Login" />
			</h:form>
			<h:form id="register">
				<label>Name<h:inputText value="#{register.name}" binding="#{name}" p:autocomplete="name" p:required=""/></label>
				<label>E-Mail<h:inputText value="#{register.email}" binding="#{email}" p:type="email" p:autocomplete="username" p:required=""/></label>
				<label>Passwort<h:inputSecret value="#{register.password}" binding="#{password}" p:autocomplete="new-password" p:required="" p:id="register-password"/></label>
				<label>Passwort wiederholen<h:inputSecret value="#{register.passwordRepeat}" p:required="" p:id="repeat-password">
					<f:validator binding="#{registerValidator}" />
					<f:attribute name="name" value="#{name}"/>
					<f:attribute name="email" value="#{email}"/>
					<f:attribute name="password" value="#{password}"/>
				</h:inputSecret>
				</label>
				<label><h:selectBooleanCheckbox value="#{register.manager}" />Ich bin ein Veranstalter</label>
				<h:commandButton action="#{register.register}" value="Register" />
			</h:form>
		</div>
	</div></h:panelGroup>
	<div class="modal"><h:form id="reserve">
		<h:inputHidden value="#{reserveTicket.event}" binding="#{eventId}" p:id="reserve-event-id"/>
		<h:panelGroup rendered="#{sessionBean.loggedIn}">
			Sie sind momentan als #{sessionBean.currentUser.name} angemeldet.
			<button id="reserve-logout" type="button">Logout</button>
		</h:panelGroup>
		<h:panelGroup rendered="#{not sessionBean.loggedIn}">
			Sie sind derzeit nicht angemeldet.
			<div class="choice">
				<div>
					Anmelden und ihre reservierten Tickets unter „Meine Tickets” verfolgen können
					<label>E-Mail<input name="email" type="email" form="reserve-login" /></label>
					<label>Passwort<input name="password" type="password" form="reserve-login" /></label>
					<button type="submit" form="reserve-login">Login</button>
				</div>
				<div>ODER</div>
				<div>Unangemeldet reservieren
					<label>Name<h:inputText value="#{reserveTicket.name}" binding="#{notAuthenticatedUser}" p:id="reserve-name" p:required="" /></label>
				</div>
			</div>
		</h:panelGroup>
		<label>Anzahl Tickets<h:inputText value="#{reserveTicket.amount}" p:type="number">
			<f:validator binding="#{reserveValidator}" />
			<f:attribute name="eventId" value="#{eventId}"/>
			<f:attribute name="notAuthenticatedUser" value="#{notAuthenticatedUser}"/>
			</h:inputText>
		</label>
		<h:commandButton action="#{reserveTicket.reserve}" value="Reservieren"/>
	</h:form></div>
	<form id="reserve-login"></form>
	<script src="scripts/makexhr.js"></script>
	<script src="scripts/jsonml.js"></script>
	<script src="scripts/main.js"></script>
</h:body>
<h:body rendered="#{eventList.errorResponse}"><messages xmlns="http://java.sun.com/jsf/html"/></h:body>
</html>